Testcase12: TP Txn Application
SJTU-IPADS/ServerlessBench pull request #30
Opened 2024-06-27 01:17 UTC by Anlarry

2024-06-28 01:24 UTC, CodingYuanLiu requested changes
Could you please add some instructions about how to use the scripts in the README?

2024-06-28 03:19 UTC, Anlarry commented
Yes, I have added instructions about deployment and testing. You can find the updated details in the [Testcase12 README.md](https://github.com/SJTU-IPADS/ServerlessBench/pull/30/files#diff-68b5a04f6658b95935f0ebb7cf72254deb7c6198eb903d94999f07d1dc881857).

2024-07-01 03:04 UTC, CodingYuanLiu approved these changes

2024-07-01 03:05 UTC, merged

2024-07-01 03:05 UTC, CodingYuanLiu commented
Thanks for your contribution!